services:
  redis:
    image: redis
    container_name: scheduler-redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    container_name: scheduler-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    container_name: scheduler-grafana
    ports:
      - "4000:3000"